services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  app:
    build:
      context: .
      target: runner
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TINA_PUBLIC_IS_LOCAL=${TINA_PUBLIC_IS_LOCAL}
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      - GITHUB_BRANCH=${GITHUB_BRANCH}
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      - TINA_TOKEN=${TINA_TOKEN}
      - TINA_SECRET_KEY=${TINA_SECRET_KEY}
      - NEXT_PUBLIC_TINA_CLIENT_ID=${NEXT_PUBLIC_TINA_CLIENT_ID}
    volumes:
      # Docker volumes for production
      - app_uploads:/app/public/uploads
      - app_content:/app/content
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo_data:
  app_uploads:
  app_content:

networks:
  app-network:
    driver: bridge
