services:
  directus:
    image: directus/directus:latest
    restart: unless-stopped
    environment:
      KEY: "${DIRECTUS_KEY}"
      SECRET: "${DIRECTUS_SECRET}"
      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "${POSTGRES_USER}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      CACHE_ENABLED: "false"
      ADMIN_EMAIL: "${DIRECTUS_ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${DIRECTUS_ADMIN_PASSWORD}"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "${CORS_ORIGIN}"
      PUBLIC_URL: "${DIRECTUS_PUBLIC_URL}"
    volumes:
      - directus_uploads:/directus/uploads
      - directus_extensions:/directus/extensions
    depends_on:
      - postgres
    networks:
      - default

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: "directus"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  app:
    image: ghcr.io/augustdg/personal-portfolio:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      DIRECTUS_URL: ${DIRECTUS_URL}
      PUBLIC_DIRECTUS_URL: "${PUBLIC_DIRECTUS_URL}"
      DIRECTUS_STATIC_TOKEN: ${DIRECTUS_STATIC_TOKEN}
    depends_on:
      - directus
    networks:
      - default

volumes:
  postgres_data:
  directus_uploads:
  directus_extensions:

networks:
  default:
