services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    volumes:
      - directus_uploads:/directus/uploads
      - directus_extensions:/directus/extensions
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"
      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
      CACHE_ENABLED: "false"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://localhost:3000"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "directus"
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DIRECTUS_URL=http://directus:8055
      - DIRECTUS_STATIC_TOKEN=${DIRECTUS_STATIC_TOKEN}
    volumes:
      # Host-based volume mounts for development
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - directus
    networks:
      - app-network
    command: npm run dev

volumes:
  postgres_data:
  directus_uploads:
  directus_extensions:

networks:
  app-network:
    driver: bridge
